networks:
  ai_network:
    driver: bridge

volumes:
  ollama_data:
  ollama_models:
  qdrant_storage:

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434" # Expose API externally
    restart: always
    networks:
      - ai_network
    volumes:
      - ollama_data:/root/.ollama
      - ollama_models:/root/.ollama/models # Persist models

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333" # Expose API externally
    restart: always
    networks:
      - ai_network
    volumes:
      - qdrant_storage:/qdrant/storage

  # Future AI services (e.g., Vector DB) can be added here
